import Link from "next/link";
import SiteHeader from "../../../components/SiteHeader";
import BrandMark from "../../../components/BrandMark";

const title = "Does the Loisach need rights of its own if people talk to each other?";
const description = "A meeting in Ohlstadt brings together municipal practice on the Loisach, the Mar Menor and the Whanganui – and asks who speaks for the river.";
const image = "/images/IMG_5090.jpeg";

export const metadata = { title: `${title} | Rights of Nature`, description, openGraph:{title,description,type:"article",url:"https://rechtedernatur.de/aktuelles/ohlstadt-loisach-rechte-der-natur/en",siteName:"Rechte der Natur",images:[{url:image,alt:"Meeting in Ohlstadt on the Loisach and Rights of Nature"}]}, twitter:{card:"summary_large_image",title,description,images:[image]} };

export default function OhlstadtLoisachEnglish(){return <main className="newsPage">
<SiteHeader section="Aktuelles" claimLead="What is moving." claimTrail="Examined. Contextualised. In motion." />
<section className="newsHero"><p className="eyebrow">Ohlstadt · 14 September 2026 · English</p><h1>{title}</h1><p className="lead">A meeting in Ohlstadt brings together three very different experiences: municipal practice on the Loisach, the rights of the Mar Menor in Spain, and the legal personhood of the Whanganui in New Zealand. In the end, the issue is less a dispute about courts than a surprisingly practical question: Who actually speaks for the river?</p></section>
<div style={{maxWidth:1100,margin:"0 auto 42px",padding:"0 28px"}}><img src={image} alt="Meeting in Ohlstadt on the Loisach and Rights of Nature" style={{display:"block",width:"100%",height:"auto",borderRadius:20}}/></div>
<article style={{maxWidth:860,margin:"0 auto",padding:"0 28px 72px",fontSize:"1.08rem",lineHeight:1.75}}>
<p><Link href="/aktuelles/ohlstadt-loisach-rechte-der-natur">Deutsch</Link> · <Link href="/aktuelles/ohlstadt-loisach-rechte-der-natur/es">Español</Link></p>
<p>Ohlstadt, 14 September 2026. Sometimes a discussion becomes interesting precisely where agreement ends.</p><p>At today’s meeting in Ohlstadt, different ideas about how rivers and other water bodies can be protected came together. The discussion was not only about abstract legal questions. It was about wastewater treatment plants, water quality, municipalities, agriculture, property owners and public authorities – and about whether a river itself needs an institutionally secured voice.</p><p>The mayor of Ohlstadt made his position clear. He is sceptical about Rights of Nature. What matters, he argued, is talking to people and finding solutions together. He referred to the construction of a wastewater treatment plant and to the municipality’s practical work.</p><blockquote style={{fontSize:"1.5rem",lineHeight:1.45,margin:"34px 0",paddingLeft:24,borderLeft:"4px solid var(--green)"}}>“We work every day to make the water of the Loisach better.”</blockquote><p>This is a serious objection to Rights of Nature. If municipalities take responsibility, implement technical solutions and bring the parties together, what would an additional legal status for the river actually improve?</p>
<h2>Eduardo Salazar: “I don't like courts”</h2><p>Eduardo Salazar responded with the experience of the Mar Menor in Spain.</p><p>His starting point was striking. Although he is a lawyer, he said:</p><blockquote style={{fontSize:"1.35rem",lineHeight:1.5,margin:"30px 0",paddingLeft:24,borderLeft:"4px solid var(--green)"}}>“Although I am a lawyer, I don't like courts. I like public participation and democracy.”</blockquote><p>This turns a common assumption on its head: Rights of Nature do not primarily have to mean going to court more often.</p><p>Salazar described the Mar Menor model instead as a form of institutional “tutorship” for the saltwater lagoon. Different participants – including fisheries, agriculture, property owners, NGOs and surrounding municipalities – are meant to work together.</p><p>The first aim is to seek consensus rather than use legal positions as a “weapon against the other”.</p><p>For a river crossing several municipalities, involving public bodies, owners and different users, such an arrangement could help organise communication on a lasting basis.</p><p><strong>Can a legal and institutional structure ensure that people keep talking to one another – while the water body itself is also represented?</strong></p>
<h2>Whanganui: the river does not end at a municipal boundary</h2><p>The experience of the Whanganui in New Zealand opened another perspective.</p><p>There, the river is not understood as a collection of separate administrative sections. It was described as a whole: <strong>“from the mountain to the sea”</strong> – including its tributaries.</p><p>This has an immediate practical consequence. Along a river there are different towns, municipalities, authorities and other jurisdictions. The river itself does not recognise those boundaries. Multiple councils and many other actors therefore have to work together.</p><p>The legal personhood of the Whanganui does not replace that cooperation. Nor do the river’s representatives simply take over all management. Their function was described in a more modest – and perhaps therefore more interesting – way: they give the river <strong>“a face and a voice”.</strong></p><p>An institutional voice for the river need not mean creating a new super-authority that displaces municipalities, water management, conservation bodies or property owners. Representation is not the same as management.</p>
<h2>“I am the river, and the river is me”</h2><p>At the same time, it would be wrong simply to transfer the Whanganui model to the Loisach.</p><p>The river’s legal personhood is embedded in a Māori cultural and spiritual understanding fundamentally different from the conventional Western understanding of a water body.</p><p>In Ohlstadt this was expressed in the phrase: <strong>“I am the river, and the river is me.”</strong></p><p>But what was said immediately afterwards was crucial: <strong>“Which puts a responsibility on us.”</strong></p><p>The relationship with the river creates not only rights. It creates responsibility.</p><p>Children learn that responsibility. They are taught to keep the river clean and to treat it in accordance with a relationship passed down through generations.</p><p>The river, and also the mountains, are understood as ancestors. We cannot and should not import this cultural, spiritual and philosophical foundation into Bavaria.</p><p><strong>But what changes when responsibility for a river no longer depends only on the goodwill of the people and institutions acting at a particular moment, but is permanently embedded in institutions?</strong></p>
<h2>Whanganui is not a conflict-free story either</h2><p>It would be equally wrong to tell a romantic story in which Rights of Nature make conflict or courts unnecessary.</p><p>In Ohlstadt, reference was made to the roughly <strong>150 years of disputes</strong> surrounding the Whanganui. Taking the government to court was explicitly mentioned. Land, rivers and mountains were contested across generations.</p><p>Dialogue, law, political struggle, cultural self-assertion and cooperation are not alternatives here. They are parts of the same history.</p><p>Rights of Nature are not merely a litigation instrument. But law must remain capable of action where dialogue and cooperation fail.</p>
<h2>Perhaps the mayor is right about part of his objection</h2><p>That is precisely why the scepticism of Ohlstadt’s mayor should not simply be argued away.</p><p>Of course people must talk to one another. Of course municipalities must take responsibility. And a river does not become cleaner merely because rights are written down on paper.</p><p>The interesting question begins one step later.</p><p>The Loisach flows through different municipalities. Different authorities and political levels are responsible for it. There is water abstraction, flood protection, agriculture, hydropower, fisheries, watercourse maintenance, settlements, infrastructure and protected areas. Interests may coincide. They may also collide.</p><p><strong>A wastewater treatment plant can be built. A river remains.</strong></p><p>And decisions about it are made again and again over decades.</p><p>What happens when the parties cannot agree?</p><p>Who then represents not the municipality, not the owner, not agriculture, not an association and not an authority – but the Loisach?</p>
<h2>From talking about water bodies to a dialogue of water bodies</h2><p>Perhaps the mayor’s sentence – <strong>“We have to talk to each other”</strong> – has more in common with the idea of a “Dialogue of Water Bodies” than it first appears.</p><p>That idea, too, is about communication. But the question shifts: <strong>Who actually belongs to this “we”?</strong></p><p>If the Whanganui, the Mar Menor and the Loisach are to enter into relationship with one another, it is not enough for people merely to talk about these water bodies. In practice, such a dialogue is necessarily mediated by people. That is precisely why the institutional question arises: under what conditions can these people actually speak for a water body rather than merely about it?</p><blockquote style={{fontSize:"1.35rem",lineHeight:1.6,margin:"32px 0",paddingLeft:24,borderLeft:"4px solid var(--green)"}}><strong>We talk about water bodies.<br/>Water bodies talk to each other.<br/>We are water bodies.</strong></blockquote><p>The middle sentence is the hardest.</p><p>A metaphor becomes a genuine dialogue of water bodies only when it is clear who may speak for a water body, what legitimises that voice, and what responsibility comes with the mandate.</p><p>This does not mean that representatives own or manage the water body or replace existing authorities. <strong>Voice is not management. Representation is not ownership. And representation is not automatically public authority.</strong></p><p>Especially when human interests collide, the water body’s voice must be sufficiently independent to bring its ecological relationships and functions into the decision.</p>
<h2>Ohlstadt as a starting point</h2><p>Perhaps the differing views at the Ohlstadt meeting are precisely what make it a productive beginning.</p><p>The mayor says: <strong>We have to talk to each other.</strong></p><p>Eduardo Salazar shows through the Mar Menor: <strong>A legal representation structure can be created precisely to enable dialogue and bring different interests together.</strong></p><p>The Whanganui experience adds: <strong>The river remains a whole even when human jurisdictions change along its course. Its representatives do not replace those institutions. They give the river a face and a voice.</strong></p><p>The “Dialogue of Water Bodies” takes these ideas one step further. If water bodies themselves are to enter into relationship with one another, their voices need a comprehensible form of representation, mandate and responsibility.</p><p>So perhaps the decisive question is not:</p><p><strong>Does the Loisach need rights, or does it need cooperation?</strong></p><p><strong>Rather:</strong></p><p><strong>How do we organise cooperation along the entire Loisach so that the river itself has a permanent voice – and how does that voice become a counterpart capable of genuinely entering into dialogue with other water bodies?</strong></p><p>After the meeting in Ohlstadt, there is no shared answer yet.</p><p>But perhaps that is exactly where a serious discussion can begin.</p>
<hr style={{margin:"52px 0 28px",border:0,borderTop:"1px solid rgba(0,0,0,.15)"}}/><p style={{fontSize:".9rem"}}><strong>Licence:</strong> This article, including the accompanying photograph, is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).</p><p style={{fontSize:".9rem"}}>The structure and parts of the wording were developed with the assistance of AI (GPT, OpenAI). Editorial responsibility: Hans Leo Bader. (CC BY-NC-SA 4.0)</p><p style={{fontSize:".9rem"}}>Photo: Hans Leo Bader – Licence: CC BY-NC-SA 4.0</p><p style={{marginTop:36}}><Link href="/aktuelles">← Aktuelles</Link></p>
</article><footer><div className="footerIdentity"><BrandMark/><div><strong>Rechte der Natur</strong><small>English</small></div></div><p>Rights of Nature and institutional representation.</p></footer></main>;}