const items=[
  {date:"09.08.2026",tag:"In Prüfung",title:"Kolumbien: neuer Flussrechte-Entwurf",text:"Ein aktueller Hinweis auf einen neuen Gesetzentwurf wird derzeit anhand amtlicher Quellen geprüft. Solange Verfahrensstand, Inhalt und institutionelle Architektur nicht belastbar geklärt sind, bleibt der Beitrag ausdrücklich als Prüfung gekennzeichnet.",href:"#"},
  {date:"2026",tag:"Hintergrund",title:"Mar Menor: Rechtspersönlichkeit allein reicht nicht",text:"Die spanische Lagune zeigt besonders deutlich, warum Anerkennung, Vertretung, institutionelle Zuständigkeit und tatsächliche Wirkung getrennt betrachtet werden müssen.",href:"/weltweit"},
  {date:"2026",tag:"Deutschland",title:"16 Länder – unterschiedliche Wege",text:"Die neue Deutschlandseite macht sichtbar, dass ein bundesweites Projekt nicht aus 16 Kopien derselben Kampagne bestehen kann. Jedes Land braucht eine eigene rechtliche und politische Prüfung.",href:"/deutschland"}
];
const labels=[
  ["Bestätigt","Aussage und Verfahrensstand sind belastbar geprüft und können als aktueller Sachstand veröffentlicht werden."],
  ["In Prüfung","Es gibt einen relevanten Hinweis, aber noch keine ausreichende Primärquellenbasis. Wir kennzeichnen das offen."],
  ["Hintergrund","Kein News-Ereignis, sondern eine Einordnung, die hilft, aktuelle Entwicklungen zu verstehen."],
  ["Kampagne","Aktuelle Entwicklung innerhalb unserer eigenen Volksbegehrens- und Plattformarbeit."]
];
function Mark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function Aktuelles(){return <main className="newsPage">
<header className="siteHeader"><a className="brand" href="/"><Mark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Aktuelles</small></span></a><nav><a href="/weltweit">Weltweit</a><a href="/deutschland">Deutschland</a><a href="/volksbegehren">Volksbegehren</a><a className="navAction" href="#beitraege">Aktuelles</a></nav></header>
<section className="heritageStrip"><span>Was sich bewegt.</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Geprüft statt nacherzählt.</span></section>
<section className="newsHero"><p className="eyebrow">Aktuelles</p><h1>Was neu ist – und wie sicher wir es wissen.</h1><p className="lead">Rechte der Natur entwickeln sich schnell. Neue Urteile, Gesetze, Initiativen und politische Debatten sind relevant – aber nicht jeder Social-Media-Post ist schon ein belastbarer Sachstand. Deshalb zeigen wir nicht nur, was neu ist, sondern auch, wie gut es geprüft ist.</p></section>
<section className="newsRule"><div><p className="sectionLabel">Redaktioneller Grundsatz</p><h2>Hinweis ist nicht Beleg.</h2></div><div><p>Wir unterscheiden zwischen bestätigten Entwicklungen, laufender Prüfung und Hintergrund. Wo der Primärquellenstand noch unklar ist, sagen wir das.</p><p>Das macht die Seite vielleicht etwas langsamer als einen Newsfeed. Dafür soll sie auch morgen noch stimmen.</p></div></section>
<section className="newsItems" id="beitraege">{items.map((item,i)=><article className="newsItem" key={item.title}><div className="newsMeta"><span>{item.date}</span><strong>{item.tag}</strong></div><div className="newsBody"><span className="newsNo">{String(i+1).padStart(2,"0")}</span><h2>{item.title}</h2><p>{item.text}</p>{item.href!=="#"?<a href={item.href}>Weiterlesen →</a>:<span className="newsPending">Vollständige Einordnung folgt nach Abschluss der Prüfung.</span>}</div></article>)}</section>
<section className="newsLabels"><div className="stateHeader"><p className="sectionLabel">Kennzeichnung</p><h2>Vier Begriffe, damit klar ist, was du gerade liest.</h2></div><div className="labelGrid">{labels.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="newsBridge"><div><p className="sectionLabel">Nicht nur Nachrichten</p><h2>Aktuelles gehört in einen größeren Zusammenhang.</h2></div><div><p>Ein neues Urteil oder Gesetz ist erst dann wirklich interessant, wenn klar wird, was es verändert: die rechtliche Stellung der Natur, ihre Vertretung, institutionelle Entscheidungen oder tatsächliche Wirkungen.</p><div className="heroActions"><a className="buttonPrimary" href="/weltweit">Internationale Fälle</a><a className="textLink" href="/deutschland">Deutschland →</a></div></div></section>
<footer><div className="footerIdentity"><Mark/><div><strong>Rechte der Natur</strong><small>Aktuelles</small></div></div><p>Aktuelle Entwicklungen mit sichtbarer Prüftiefe.</p><span>Entwurf · Preview</span></footer>
</main>}
