import Link from "next/link";
import SiteHeader from "../../components/SiteHeader";
import BrandMark from "../../components/BrandMark";

const title = "Braucht die Loisach eigene Rechte, wenn die Menschen miteinander reden?";
const description = "Ein Treffen in Ohlstadt bringt kommunale Praxis an der Loisach, das Mar Menor und den Whanganui zusammen – und stellt die Frage, wer für den Fluss spricht.";
const image = "/images/IMG_5090.jpeg";

export const metadata = {
  title: `${title} | Rechte der Natur`,
  description,
  openGraph: {
    title,
    description,
    type: "article",
    url: "https://rechtedernatur.de/aktuelles/ohlstadt-loisach-rechte-der-natur",
    siteName: "Rechte der Natur",
    images: [{ url: image, alt: "Treffen in Ohlstadt zur Loisach und zu Rechten der Natur" }],
  },
  twitter: { card: "summary_large_image", title, description, images: [image] },
};

export default function OhlstadtLoisachArtikel() {
  return (
    <main className="newsPage">
      <SiteHeader section="Aktuelles" claimLead="Was sich bewegt." claimTrail="Geprüft. Eingeordnet. In Bewegung." />
      <section className="newsHero">
        <p className="eyebrow">Ohlstadt · 14. September 2026</p>
        <h1>Braucht die Loisach eigene Rechte, wenn die Menschen miteinander reden?</h1>
        <p className="lead">Ein Treffen in Ohlstadt bringt drei sehr unterschiedliche Erfahrungen zusammen: kommunale Praxis an der Loisach, die Rechte des Mar Menor in Spanien und die Rechtspersönlichkeit des Whanganui in Neuseeland. Am Ende steht weniger ein Streit über Gerichte als eine überraschend praktische Frage: Wer spricht eigentlich für den Fluss?</p>
      </section>
      <div style={{maxWidth:1100, margin:"0 auto 42px", padding:"0 28px"}}><img src="/images/IMG_5090.jpeg" alt="Treffen in Ohlstadt zur Loisach und zu Rechten der Natur" style={{display:"block", width:"100%", height:"auto", borderRadius:20}} /></div>
      <article style={{maxWidth:860, margin:"0 auto", padding:"0 28px 72px", fontSize:"1.08rem", lineHeight:1.75}}>
        <p>Ohlstadt, 14. September 2026. Manchmal wird eine Diskussion gerade dort interessant, wo keine Einigkeit entsteht.</p>
        <p>Beim heutigen Treffen in Ohlstadt trafen unterschiedliche Vorstellungen davon aufeinander, wie Flüsse und andere Gewässer geschützt werden können. Dabei ging es nicht nur um abstrakte Rechtsfragen. Es ging um Kläranlagen, Wasserqualität, Gemeinden, Landwirtschaft, Eigentümer, Behörden – und um die Frage, ob ein Fluss selbst eine institutionell abgesicherte Stimme braucht.</p>
        <p>Der Bürgermeister von Ohlstadt machte seine Position deutlich. Er steht Rechten der Natur skeptisch gegenüber. Entscheidend sei, mit den Menschen zu reden und gemeinsam Lösungen zu finden. Als Beispiel verwies er auf den Bau einer Kläranlage und auf die praktische Arbeit der Gemeinde.</p>
        <blockquote style={{fontSize:"1.5rem", lineHeight:1.45, margin:"34px 0", paddingLeft:24, borderLeft:"4px solid var(--green)"}}>„Wir arbeiten jeden Tag daran, das Wasser der Loisach besser zu machen.“</blockquote>
        <p>Das ist ein ernst zu nehmender Einwand gegen Rechte der Natur. Denn wenn Kommunen Verantwortung übernehmen, technische Lösungen umsetzen und Beteiligte miteinander sprechen: Was würde eine zusätzliche Rechtsstellung des Flusses tatsächlich verbessern?</p>
        <h2>Eduardo Salazar: „I don't like courts“</h2>
        <p>Darauf antwortete Eduardo Salazar mit den Erfahrungen des Mar Menor in Spanien.</p><p>Bemerkenswert war schon sein Ausgangspunkt. Obwohl er Jurist ist, sagte er:</p>
        <blockquote style={{fontSize:"1.35rem", lineHeight:1.5, margin:"30px 0", paddingLeft:24, borderLeft:"4px solid var(--green)"}}>„Although I am a lawyer, I don't like courts. I like public participation and democracy.“</blockquote>
        <p>Damit stellte er eine verbreitete Vorstellung auf den Kopf: Rechte der Natur müssen nicht in erster Linie bedeuten, häufiger vor Gericht zu ziehen.</p><p>Eduardo Salazar beschrieb die Konstruktion beim Mar Menor vielmehr als eine Art institutionelle „Tutorship“ für die Salzwasserlagune. Unterschiedliche Beteiligte – unter anderem Fischerei, Landwirtschaft, Eigentümer, NGOs und die umliegenden Gemeinden – sollen miteinander arbeiten.</p><p>Zunächst soll versucht werden, Konsens herzustellen, statt rechtliche Positionen als „weapon against the other“, als Waffe gegeneinander, einzusetzen.</p><p>Gerade bei einem Fluss, der mehrere Gemeinden durchquert, bei dem staatliche Stellen, Eigentümer und unterschiedliche Nutzer beteiligt sind, könne eine solche Konstruktion helfen, Kommunikation dauerhaft zu organisieren.</p><p><strong>Kann eine rechtliche und institutionelle Struktur dafür sorgen, dass dauerhaft miteinander geredet wird – und dass dabei auch das Gewässer selbst vertreten ist?</strong></p>
        <h2>Whanganui: Der Fluss endet nicht an der Gemeindegrenze</h2>
        <p>Die Erfahrungen vom Whanganui in Neuseeland eröffneten noch eine andere Perspektive.</p><p>Dort wird der Fluss nicht als Ansammlung einzelner Verwaltungsabschnitte verstanden. Beschrieben wurde er als ein Ganzes: <strong>„from the mountain to the sea“</strong> – vom Berg bis zum Meer, einschließlich seiner Zuflüsse.</p><p>Das hat eine unmittelbar praktische Konsequenz. Entlang eines Flusses gibt es verschiedene Städte, Gemeinden, Behörden und andere Zuständigkeiten. Der Fluss selbst kennt diese Grenzen nicht. Deshalb müssen mehrere Councils und zahlreiche weitere Akteure zusammenarbeiten.</p><p>Die Rechtspersönlichkeit des Whanganui ersetzt diese Zusammenarbeit gerade nicht. Auch die Repräsentanten des Flusses übernehmen nicht einfach das gesamte Management. Ihre Funktion wurde wesentlich bescheidener – und vielleicht gerade deshalb interessant – beschrieben: Sie geben dem Fluss <strong>„a face and a voice“</strong> – ein Gesicht und eine Stimme.</p><p>Eine institutionelle Stimme des Flusses muss nicht bedeuten, eine neue Superbehörde zu schaffen, die Gemeinden, Wasserwirtschaft, Naturschutz oder Eigentümer verdrängt. Repräsentation ist nicht dasselbe wie Management.</p>
        <h2>„I am the river, and the river is me“</h2>
        <p>Gleichzeitig wäre es falsch, das Modell des Whanganui einfach auf die Loisach übertragen zu wollen.</p><p>Die Rechtspersönlichkeit des Flusses ist dort in ein kulturelles und spirituelles Verständnis der Māori eingebettet, das sich fundamental von unserem üblichen westlichen Verständnis eines Gewässers unterscheidet.</p><p>In Ohlstadt wurde dafür ein Satz wiedergegeben: <strong>„I am the river, and the river is me.“</strong></p><p>Entscheidend war aber, was unmittelbar danach gesagt wurde: <strong>„Which puts a responsibility on us.“</strong></p><p>Aus der Beziehung zum Fluss entstehen nicht nur Rechte. Es entsteht Verantwortung.</p><p>Kinder lernen diese Verantwortung. Sie sollen dafür sorgen, dass der Fluss sauber bleibt und dass mit ihm entsprechend dieser über Generationen vermittelten Beziehung umgegangen wird.</p><p>Der Fluss und auch die Berge werden dabei als Vorfahren verstanden. Dieses kulturelle, spirituelle und philosophische Fundament können und sollten wir nicht nach Bayern importieren.</p><p><strong>Was verändert sich, wenn Verantwortung für einen Fluss nicht nur vom guten Willen der jeweils handelnden Menschen und Institutionen abhängt, sondern dauerhaft institutionell verankert wird?</strong></p>
        <h2>Auch Whanganui ist keine konfliktfreie Geschichte</h2>
        <p>Ebenso falsch wäre eine romantische Erzählung, nach der Rechte der Natur Konflikte oder Gerichte überflüssig machen.</p><p>In Ohlstadt wurde an die rund <strong>150 Jahre dauernden Auseinandersetzungen</strong> um den Whanganui erinnert. Es wurde ausdrücklich davon gesprochen, die Regierung vor Gericht zu bringen. Über Generationen wurde um Land, Flüsse und Berge gekämpft.</p><p>Dialog, Recht, politische Auseinandersetzung, kulturelle Selbstbehauptung und Kooperation stehen hier nicht alternativ nebeneinander. Sie gehören zu derselben Geschichte.</p><p>Rechte der Natur sind kein Klageinstrument. Aber Recht muss dort handlungsfähig bleiben, wo Dialog und Kooperation scheitern.</p>
        <h2>Vielleicht hat der Bürgermeister mit einem Teil seines Einwands recht</h2>
        <p>Gerade deshalb lohnt es sich, die Skepsis des Ohlstädter Bürgermeisters nicht wegzudiskutieren.</p><p>Natürlich müssen Menschen miteinander reden. Natürlich brauchen wir Gemeinden, die Verantwortung übernehmen. Und selbstverständlich wird ein Fluss nicht dadurch sauberer, dass man ihm auf dem Papier Rechte zuspricht.</p><p>Die interessante Frage beginnt einen Schritt später.</p><p>Die Loisach fließt durch unterschiedliche Gemeinden. Für sie sind unterschiedliche Behörden und politische Ebenen zuständig. Es gibt Wasserentnahme, Hochwasserschutz, Landwirtschaft, Wasserkraft, Fischerei, Gewässerunterhaltung, Siedlungen, Infrastruktur und Schutzgebiete. Interessen können übereinstimmen. Sie können aber auch kollidieren.</p><p><strong>Eine Kläranlage lässt sich bauen. Ein Fluss bleibt.</strong></p><p>Und Entscheidungen über ihn werden über Jahrzehnte immer wieder neu getroffen.</p><p>Was geschieht also, wenn die Beteiligten sich einmal nicht einigen?</p><p>Wer vertritt dann nicht die Gemeinde, nicht den Eigentümer, nicht die Landwirtschaft, nicht einen Verband und nicht eine Behörde – sondern die Loisach?</p>
        <h2>Vom Gespräch über Gewässer zum Dialog der Gewässer</h2>
        <p>Vielleicht steckt in dem Satz des Bürgermeisters – <strong>„Wir müssen miteinander reden“</strong> – mehr Gemeinsamkeit mit dem Gedanken des „Dialogs der Gewässer“, als es zunächst scheint.</p><p>Auch dort geht es um Kommunikation. Aber die Frage verschiebt sich: <strong>Wer gehört eigentlich zu diesem „Wir“?</strong></p><p>Wenn Whanganui, Mar Menor und Loisach miteinander in Beziehung treten sollen, genügt es nicht, dass Menschen nur über diese Gewässer sprechen. Praktisch geschieht ein solcher Dialog notwendigerweise vermittelt durch Menschen. Gerade deshalb stellt sich die institutionelle Frage, unter welchen Voraussetzungen diese Menschen tatsächlich für ein Gewässer sprechen können – und nicht lediglich über es.</p>
        <blockquote style={{fontSize:"1.35rem", lineHeight:1.6, margin:"32px 0", paddingLeft:24, borderLeft:"4px solid var(--green)"}}><strong>We talk about water bodies.<br/>Water bodies talk to each other.<br/>We are water bodies.</strong></blockquote>
        <p>Der schwierigste Satz ist der mittlere.</p><p>Denn aus einer Metapher wird erst dann ein wirklicher Dialog der Gewässer, wenn nachvollziehbar ist, wer für ein Gewässer sprechen kann, wodurch diese Stimme legitimiert wird und welche Verantwortung mit diesem Mandat verbunden ist.</p><p>Das bedeutet nicht, dass Repräsentanten das Gewässer besitzen, verwalten oder an die Stelle bestehender Behörden treten. <strong>Stimme ist nicht Management. Repräsentation ist nicht Eigentum. Und Repräsentation ist nicht automatisch behördliche Zuständigkeit.</strong></p><p>Gerade wenn menschliche Interessen kollidieren, muss eine Stimme des Gewässers eigenständig genug sein, um dessen ökologische Beziehungen und Funktionen in die Entscheidung einzubringen.</p>
        <h2>Ohlstadt als Ausgangspunkt</h2>
        <p>Vielleicht liegt gerade in der unterschiedlichen Sichtweise beim Treffen in Ohlstadt ein produktiver Anfang.</p><p>Der Bürgermeister sagt: <strong>Wir müssen miteinander reden.</strong></p><p>Eduardo Salazar zeigt am Mar Menor: <strong>Eine rechtliche Repräsentationsstruktur kann gerade dafür geschaffen werden, miteinander zu reden und unterschiedliche Interessen zusammenzubringen.</strong></p><p>Die Erfahrung des Whanganui ergänzt: <strong>Der Fluss bleibt eine Einheit, auch wenn die menschlichen Zuständigkeiten entlang seines Laufes wechseln. Seine Repräsentanten ersetzen diese Institutionen nicht. Sie geben dem Fluss Gesicht und Stimme.</strong></p><p>Der „Dialog der Gewässer“ führt diese Gedanken noch einen Schritt weiter. Wenn Gewässer selbst miteinander in Beziehung treten sollen, brauchen ihre Stimmen eine nachvollziehbare Form von Repräsentation, Mandat und Verantwortung.</p>
        <p>Damit lautet die entscheidende Frage möglicherweise gar nicht:</p>
        <p style={{fontSize:"1.2rem", margin:"24px 0"}}><strong>Braucht die Loisach Rechte oder braucht sie Zusammenarbeit?</strong></p>
        <p><strong>Sondern:</strong></p>
        <p style={{fontSize:"1.2rem", margin:"24px 0"}}><strong>Wie organisieren wir die Zusammenarbeit entlang der gesamten Loisach so, dass der Fluss selbst dauerhaft eine Stimme besitzt – und wie wird aus dieser Stimme ein Gegenüber, das mit anderen Gewässern tatsächlich in einen Dialog treten kann?</strong></p>
        <p>Auf diese Frage gibt es nach dem Treffen in Ohlstadt noch keine gemeinsame Antwort.</p><p>Aber vielleicht ist genau das der Punkt, an dem eine ernsthafte Diskussion beginnen kann.</p>
        <hr style={{margin:"52px 0 28px", border:0, borderTop:"1px solid rgba(0,0,0,.15)"}} />
        <p style={{fontSize:".9rem"}}><strong>Lizenzhinweis:</strong> Dieser Beitrag einschließlich des begleitenden Fotos steht unter der Lizenz Creative Commons Namensnennung – Nicht kommerziell 4.0 International (CC BY-NC-SA 4.0).</p><p style={{fontSize:".9rem"}}>Struktur und Teile der Formulierung dieses Textes wurden mithilfe von KI (GPT, OpenAI) entwickelt. Inhaltliche Verantwortung: Hans Leo Bader. (CC BY-NC-SA 4.0)</p><p style={{fontSize:".9rem"}}>Foto: Hans Leo Bader – Lizenz: CC BY-NC-SA 4.0</p><p style={{marginTop:36}}><Link href="/aktuelles">← Zurück zu Aktuelles</Link></p>
      </article>
      <footer><div className="footerIdentity"><BrandMark/><div><strong>Rechte der Natur</strong><small>Aktuelles</small></div></div><p>Aktuelle Entwicklungen für Rechte der Natur und die Volksbegehren.</p><span>Entwurf · Preview</span></footer>
    </main>
  );
}
