const stories=[{place:"Spanien",title:"Mar Menor",text:"Eine Lagune bekommt eigene Rechte. Seit 2022 ist das Mar Menor in Spanien Rechtssubjekt – ein außergewöhnlicher Versuch, ein bedrohtes Ökosystem anders zu schützen.",mark:"Wasser"},{place:"Aotearoa / Neuseeland",title:"Whanganui",text:"Der Fluss ist mehr als Wasser zwischen zwei Ufern. Seine rechtliche Anerkennung verbindet staatliches Recht mit der Beziehung der Māori zu einem lebendigen Ganzen.",mark:"Fluss"},{place:"Ecuador",title:"Natur in der Verfassung",text:"Seit 2008 erkennt die Verfassung Rechte der Natur an. Was daraus folgt, entscheidet sich nicht nur im Gesetzestext, sondern in Gerichten, Behörden und konkreten Konflikten.",mark:"Land"}];
const states=["Baden-Württemberg","Bayern","Berlin","Brandenburg","Bremen","Hamburg","Hessen","Mecklenburg-Vorpommern","Niedersachsen","Nordrhein-Westfalen","Rheinland-Pfalz","Saarland","Sachsen","Sachsen-Anhalt","Schleswig-Holstein","Thüringen"];
const legacyStates=["Bayern","Berlin","Thüringen","Sachsen","Niedersachsen","Hamburg","Baden-Württemberg"];
function BrandMark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function Home(){return <main id="top">
<header className="siteHeader"><a className="brand" href="#top" aria-label="Rechte der Natur – Startseite"><BrandMark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Das Volksbegehren</small></span></a><nav aria-label="Hauptnavigation"><a href="#idee">Die Idee</a><a href="#weltweit">Weltweit</a><a href="/deutschland">Deutschland</a><a href="/volksbegehren">Volksbegehren</a><a href="#geschichte">Unsere Geschichte</a><a className="navAction" href="#mitmachen">Mitmachen</a></nav></header>
<section className="heritageStrip"><span>Gib der Natur Recht.</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Seit Bayern. Für die Mitwelt.</span></section>
<section className="hero"><div className="heroCopy"><p className="eyebrow">Rechte der Natur</p><h1>Was wäre, wenn ein Fluss eigene Rechte hätte?</h1><p className="lead">Wir schützen Natur – und behandeln sie im Recht trotzdem meist als Sache, Eigentum oder Ressource. Weltweit wächst eine andere Idee: Natur kann eigene Rechte haben.</p><div className="heroActions"><a className="buttonPrimary" href="#idee">Verstehen, worum es geht</a><a className="textLink" href="/deutschland">Was heißt das für Deutschland? →</a></div></div><div className="heroNature" aria-hidden="true"><div className="sun"/><div className="river riverOne"/><div className="river riverTwo"/><div className="land landOne"/><div className="land landTwo"/><span>Isar</span><span>Loisach</span><span>Lech</span><div className="heroSeal"><BrandMark/><em>Eine Stimme<br/>für die Mitwelt</em></div></div></section>
<section className="plainIdea" id="idee"><p className="sectionLabel">Eine Stimme für Flüsse, Wälder und Ökosysteme</p><h2>Natur soll nicht nur geschützt werden, weil sie uns nützt.</h2><p className="bigText">Ein Wald, ein Fluss oder ein Ökosystem kann einen eigenen Wert haben – und dieser Wert kann im Recht eine eigene Stimme bekommen.</p></section>
<section className="explainGrid"><article><span className="symbol">01</span><h3>Eigene Rechte</h3><p>Natur wird nicht nur zum Objekt menschlicher Interessen. Ihre Existenz, Regeneration und ökologischen Funktionen können selbst rechtlich zählen.</p></article><article><span className="symbol">02</span><h3>Jemand spricht für sie</h3><p>Ein Fluss geht natürlich nicht ins Rathaus. Menschen oder Institutionen können seine Rechte vertreten – ähnlich wie wir auch andere nicht selbst handlungsfähige Rechtsträger vertreten.</p></article><article><span className="symbol">03</span><h3>Kein Zauberstab</h3><p>Ein Recht allein rettet noch keinen Wald. Entscheidend ist, ob es ernst genommen, vertreten und bei realen Entscheidungen tatsächlich berücksichtigt wird.</p></article></section>
<section className="questionBand"><p>Der eigentliche Perspektivwechsel</p><h2>Nicht nur: „Was dürfen wir mit der Natur tun?“</h2><strong>Sondern: „Was braucht sie, um zu leben?“</strong></section>
<section className="world" id="weltweit"><div className="sectionIntro"><p className="sectionLabel">Weltweit</p><h2>Die Idee ist längst Wirklichkeit.</h2><p>Aber nicht überall auf dieselbe Weise. Genau deshalb lohnt sich der Blick auf die Erfahrungen.</p></div><div className="storyGrid">{stories.map(s=><article className="story" key={s.title}><div className={`storyVisual visual${s.mark}`}><span>{s.mark}</span></div><div className="storyCopy"><span className="place">{s.place}</span><h3>{s.title}</h3><p>{s.text}</p><span className="coming">Mehr dazu entsteht hier →</span></div></article>)}</div></section>
<section className="campaignIdea" id="geschichte"><div className="campaignHeadline"><span>Woher wir kommen</span><h2>Aus einer bayerischen Initiative wurde eine größere Frage.</h2></div><div className="campaignCopy"><p>Die frühere Kampagnenseite entstand aus dem Volksbegehren in Bayern. Ihr Leitmotiv war einfach: der natürlichen Mitwelt eine eigene rechtliche Stimme zu geben – zunächst in der Bayerischen Verfassung.</p><p>Schon damals war Bayern nicht als Endpunkt gedacht. Neben Bayern wurden auf der alten Plattform auch Berlin, Thüringen, Sachsen, Niedersachsen, Hamburg und Baden-Württemberg als weitere mögliche Volksbegehren geführt.</p><a href="https://gibdernaturrecht.muc-mib.de" target="_blank" rel="noreferrer">Die historische Website ansehen →</a></div></section>
<section className="stateSection"><div className="stateHeader"><p className="sectionLabel">Die erste Landkarte</p><h2>Die Idee war schon früh größer als Bayern.</h2><p>Diese sieben Länder gehören zur dokumentierten Entstehungsgeschichte. Ihr damaliger Status ist historisch – nicht automatisch der heutige Arbeitsstand.</p></div><div className="stateGrid">{legacyStates.map((s,i)=><article className={`stateCard ${s==="Bayern"?"stateActive":""}`} key={s}><span>{String(i+1).padStart(2,"0")}</span><h3>{s}</h3><p>{s==="Bayern"?"Ausgangspunkt der Volksbegehrensinitiative":"Auf der früheren Plattform als Entwurfsland geführt"}</p><strong>Historische Kampagnenspur</strong></article>)}</div></section>
<section className="germanyLead" id="deutschland"><div className="germanyLeadCopy"><p className="sectionLabel">Der nächste Horizont</p><h2>16 Länder. Eine große Frage.</h2><p>Heute können wir die ursprüngliche Idee neu und sauberer denken: nicht als Kopie einer Bayern-Kampagne, sondern als gemeinsame Plattform, die für jedes Bundesland den passenden rechtlichen und politischen Weg entwickelt.</p><div className="heroActions"><a className="buttonPrimary" href="/deutschland">Deutschland ansehen</a><a className="textLink" href="/volksbegehren">Zur Kampagnenarchitektur →</a></div></div><div className="sixteen">16</div></section>
<section className="campaignIdea"><div className="campaignHeadline"><span>Die neue Architektur</span><h2>Nicht ein Volksbegehren. Ein lernendes Netz aus vielen möglichen Wegen.</h2></div><div className="campaignCopy"><p>Für jedes Bundesland muss neu geprüft werden, was rechtlich möglich, politisch sinnvoll und gesellschaftlich tragfähig ist.</p><p>Die gemeinsame Plattform kann Wissen, Gestaltung, Materialien und Erfahrungen teilen. Die konkrete Kampagne muss trotzdem zum jeweiligen Land passen.</p><a href="/volksbegehren">Zur gemeinsamen Volksbegehren-Plattform →</a></div></section>
<section className="stateSection"><div className="stateHeader"><p className="sectionLabel">16 Länder</p><h2>Eine gemeinsame Plattform. Sechzehn eigenständige Wege.</h2><p>Noch ist das eine Landkarte der Möglichkeiten – keine Behauptung über bereits laufende Kampagnen.</p></div><div className="stateGrid">{states.map((s,i)=><article className={`stateCard ${s==="Bayern"?"stateActive":""}`} key={s}><span>{String(i+1).padStart(2,"0")}</span><h3>{s}</h3><p>{s==="Bayern"?"Ausgangspunkt · Volksbegehren und Verfassungsarbeit":"Perspektive · rechtlicher und politischer Weg noch zu entwickeln"}</p>{s==="Bayern"?<a href="/volksbegehren/bayern"><strong>Bayern ansehen →</strong></a>:<strong>Noch offen</strong>}</article>)}</div></section>
<section className="bavariaFeature"><div className="bavariaNumber"><BrandMark/></div><div className="bavariaCopy"><p className="sectionLabel">Der erste Weg</p><h2>Bayern: Eine Stimme für Isar, Lech und Loisach.</h2><p>Das Volksbegehren „Rechte der Natur“ war der Ausgangspunkt. Die alte Kampagne, ihre Materialien und die späteren rechtlichen Arbeiten bleiben erreichbar – aber die neue Plattform erzählt diese Geschichte verständlicher, aktueller und mit Blick auf das, was daraus noch entstehen kann.</p><div className="bavariaLinks"><a href="/volksbegehren/bayern">Neue Bayern-Seite ansehen →</a><a href="https://gibdernaturrecht.muc-mib.de/vb_bayern" target="_blank" rel="noreferrer">Historische Originalseite →</a></div></div></section>
<section className="campaignCall"><span className="tiny">Gib der Natur Recht.</span><h2>Die Geschichte bleibt. Der nächste Schritt wird größer.</h2><p>Wir müssen nicht alles neu erfinden. Wir nehmen mit, was funktioniert hat, korrigieren, was wir heute genauer wissen, und bauen daraus eine Plattform, die Menschen erreicht und zugleich fachlich belastbar bleibt.</p></section>
<section className="join" id="mitmachen"><p className="sectionLabel">Mitdenken. Mitreden. Mitmachen.</p><h2>Recht verändert sich, wenn Menschen anfangen, anders zu fragen.</h2><div className="joinLinks"><a href="/deutschland">Deutschland: Stand und 16 Länder <span>→</span></a><a href="/volksbegehren">Volksbegehren: gemeinsame Architektur <span>→</span></a><a href="https://systemische-rechtsentwicklung.de" target="_blank" rel="noreferrer">Fachlich tiefer einsteigen <span>→</span></a></div></section>
<footer><div className="footerIdentity"><BrandMark/><div><strong>Rechte der Natur</strong><small>Das Volksbegehren</small></div></div><p>Eine neue Perspektive auf Recht, Verantwortung und unsere Mitwelt.</p><span>Entwurf · Preview</span></footer>
</main>}
