const states=[
["Baden-Württemberg","Historische Spur"],["Bayern","Referenzfall"],["Berlin","Historische Spur"],["Brandenburg","Noch offen"],["Bremen","Noch offen"],["Hamburg","Historische Spur"],["Hessen","Noch offen"],["Mecklenburg-Vorpommern","Noch offen"],["Niedersachsen","Historische Spur"],["Nordrhein-Westfalen","Noch offen"],["Rheinland-Pfalz","Noch offen"],["Saarland","Noch offen"],["Sachsen","Historische Spur"],["Sachsen-Anhalt","Noch offen"],["Schleswig-Holstein","Noch offen"],["Thüringen","Historische Spur"]
];
const status=[
["Noch offen","Noch keine aktuelle Länderprüfung auf dieser Plattform."],
["Historische Spur","Das Land war bereits Teil der früheren Volksbegehrens-Idee. Das sagt noch nichts über den heutigen Stand."],
["Rechtliche Prüfung","Verfassung, direkte Demokratie und mögliche Regelungswege werden konkret geprüft."],
["Netzwerkaufbau","Menschen und Organisationen im Land beginnen, einen tragfähigen Weg zu entwickeln."],
["Vorbereitung","Ziel, Text, Verfahren und Kampagnenstruktur sind so weit geklärt, dass eine Initiative vorbereitet werden kann."],
["Aktive Kampagne","Eine konkrete Initiative läuft. Dieser Status darf erst verwendet werden, wenn das tatsächlich der Fall ist."]
];
function Mark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function Deutschland(){return <main className="countryPage">
<header className="siteHeader"><a className="brand" href="/"><Mark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Deutschland</small></span></a><nav><a href="/">Die Idee</a><a href="/volksbegehren">Volksbegehren</a><a href="/volksbegehren/bayern">Bayern</a><a className="navAction" href="#laender">16 Länder</a></nav></header>
<section className="heritageStrip"><span>Gib der Natur Recht.</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Deutschland neu denken.</span></section>
<section className="deHero"><div><p className="eyebrow">Deutschland</p><h1>Ein Land. 16 Länder. Viele mögliche Wege.</h1><p className="lead">Rechte der Natur lassen sich in Deutschland nicht mit einem einzigen Kampagnenrezept verwirklichen. Verfassungen, Verfahren direkter Demokratie, politische Konstellationen und Landschaften unterscheiden sich. Genau deshalb beginnen wir mit einer Landkarte – nicht mit fertigen Antworten.</p><div className="heroActions"><a className="buttonPrimary" href="#laender">Die Länder ansehen</a><a className="textLink" href="/volksbegehren">Zur Kampagnenidee →</a></div></div><div className="deBig16">16</div></section>
<section className="dePrinciple"><p className="sectionLabel">Unser Grundsatz</p><h2>Nicht überall dasselbe fordern. Überall dieselbe Frage ernst nehmen.</h2><p>Welche rechtliche Form stärkt die Eigenbelange der Mitwelt in diesem Land tatsächlich? Erst wenn diese Frage beantwortet ist, sollte aus einer Idee eine Kampagne werden.</p></section>
<section className="deThree"><article><span>01</span><h3>Recht prüfen</h3><p>Was erlaubt die jeweilige Landesverfassung? Welche Form direkter Demokratie gibt es? Wo liegen Grenzen und echte Gestaltungsspielräume?</p></article><article><span>02</span><h3>Land verstehen</h3><p>Welche Ökosysteme, Konflikte und Erfahrungen prägen das Bundesland? Eine Kampagne muss einen Ort und seine Menschen verstehen.</p></article><article><span>03</span><h3>Dann erst aktivieren</h3><p>Eine Initiative wird nicht dadurch gut, dass sie schnell startet. Sie braucht ein belastbares Ziel, Menschen vor Ort und einen Weg, der rechtlich wie politisch trägt.</p></article></section>
<section className="deMap" id="laender"><div className="stateHeader"><p className="sectionLabel">Arbeitslandkarte</p><h2>16 Bundesländer. Der Stand darf unterschiedlich sein.</h2><p>Diese Übersicht ist absichtlich zurückhaltend. „Historische Spur“ bezeichnet die frühere Kampagnenarchitektur; nur Bayern ist derzeit als ausgearbeiteter Referenzfall dieser neuen Plattform dargestellt.</p></div><div className="stateGrid">{states.map(([name,state],i)=><article className={`stateCard ${name==="Bayern"?"stateActive":""}`} key={name}><span>{String(i+1).padStart(2,"0")}</span><h3>{name}</h3><p>{state}</p>{name==="Bayern"?<a href="/volksbegehren/bayern"><strong>Referenzfall ansehen →</strong></a>:<strong>{state}</strong>}</article>)}</div></section>
<section className="statusSection"><div className="statusIntro"><p className="sectionLabel">Statuslogik</p><h2>Wir zeigen nur, was wirklich da ist.</h2><p>Damit aus einer ambitionierten Plattform keine Selbsttäuschung wird, bekommt jedes Land einen nachvollziehbaren Arbeitsstatus.</p></div><div className="statusList">{status.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="deBayern"><div><p className="sectionLabel">Referenzfall Bayern</p><h2>Wir fangen nicht bei null an.</h2></div><div><p>Das bayerische Volksbegehren ist Herkunft, Erfahrung und Lernmaterial. Es zeigt, was bereits entwickelt wurde – und zugleich, welche Fragen wir heute genauer stellen.</p><a className="buttonPrimary" href="/volksbegehren/bayern">Bayern ansehen →</a></div></section>
<section className="campaignCall"><span className="tiny">Der Horizont</span><h2>16 Länder sind kein Versprechen. Sie sind eine Einladung zum Denken.</h2><p>Wo ein tragfähiger Weg entsteht, kann aus der Landkarte eine Initiative werden. Wo die Voraussetzungen fehlen, bleibt sie zunächst eine offene Frage. Beides gehört zu seriöser Kampagnenarbeit.</p></section>
<section className="join"><p className="sectionLabel">Ein Land weiterdenken</p><h2>Du kennst dein Bundesland besser als wir?</h2><div className="joinLinks"><a href="/volksbegehren">Wie die gemeinsame Kampagnenarchitektur funktioniert <span>→</span></a><a href="/volksbegehren/bayern">Was wir aus Bayern lernen <span>→</span></a><a href="/">Zurück zur Idee der Rechte der Natur <span>→</span></a></div></section>
<footer><div className="footerIdentity"><Mark/><div><strong>Rechte der Natur</strong><small>Deutschland</small></div></div><p>Eine Plattform für unterschiedliche rechtliche und politische Wege.</p><span>Entwurf · Preview</span></footer>
</main>}
