import "../participation.css";

function Mark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function UeberUns(){return <main className="aboutPage">
<header className="siteHeader"><a className="brand" href="/"><Mark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Über uns</small></span></a><nav><a href="/aktuelles">Aktuelles</a><a href="/weltweit">Weltweit</a><a href="/deutschland">Deutschland</a><a href="/mitmachen">Mitmachen</a></nav></header>
<section className="heritageStrip"><span>Gib der Natur Recht.</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Aus einer Kampagne wurde eine Plattform.</span></section>
<section className="aboutHero"><p className="eyebrow">Über uns</p><h1>Wir kommen aus einer Kampagne. Heute fragen wir breiter.</h1><p className="lead">Die Arbeit begann mit dem Volksbegehren „Rechte der Natur“ in Bayern. Daraus entstanden rechtliche Auseinandersetzung, internationale Recherche und die Frage, wie Rechte der Natur tatsächlich wirksam werden können.</p></section>
<section className="aboutOrigin"><div><p className="sectionLabel">Herkunft</p><h2>Bayern war der Anfang, nicht das Ende.</h2></div><div><p>Das Volksbegehren wollte Rechte der Natur in der Bayerischen Verfassung verankern. Die Kampagne brachte Menschen, juristische Fragen und internationale Beispiele zusammen.</p><p>Mit der Zeit wurde deutlich: Die Frage ist größer als ein einzelner Verfassungstext. Anerkennung allein sagt noch wenig darüber, wer Rechte vertritt, wie Behörden und Gerichte damit umgehen und ob sich Entscheidungen tatsächlich verändern.</p><a href="/volksbegehren/bayern">Zur Bayern-Geschichte →</a></div></section>
<section className="aboutLayers"><article><span>01</span><h3>Kampagne</h3><p>Die Rechte-der-Natur-Plattform erklärt, verbindet und kann konkrete politische Initiativen unterstützen.</p></article><article><span>02</span><h3>Netzwerk</h3><p>Die Arbeit lebt von Menschen und Organisationen, die unterschiedliche Erfahrungen, Perspektiven und Kompetenzen einbringen.</p></article><article><span>03</span><h3>Fachliche Vertiefung</h3><p>Die Systemische Rechtsentwicklung ist eine eigenständige fachliche Arbeit. Sie dient nicht dazu, jedes Ergebnis zugunsten von Rechte der Natur zu begründen.</p></article></section>
<section className="aboutSeparation"><div><p className="sectionLabel">Warum diese Trennung wichtig ist</p><h2>Eine Methode ist keine Kampagnenabteilung.</h2></div><div><p>Wenn fachliche Prüfung nur bestätigen dürfte, was die Kampagne ohnehin möchte, wäre sie wertlos. Deshalb bleiben Kampagnenplattform und Systemische Rechtsentwicklung organisatorisch und inhaltlich unterscheidbar.</p><p>Das Ergebnis einer Prüfung kann sein, dass Rechte der Natur sinnvoll sind. Es kann aber auch sein, dass eine andere Rechtsform, ein anderes Verfahren oder eine institutionelle Veränderung geeigneter ist.</p><a href="https://systemische-rechtsentwicklung.de" target="_blank" rel="noreferrer">Zur Systemischen Rechtsentwicklung →</a></div></section>
<section className="aboutPrinciples"><p className="sectionLabel">Was uns wichtig ist</p><div><strong>Quellen vor Behauptungen.</strong><strong>Wirkung vor Symbolik.</strong><strong>Mitwelt nicht nur als Ressource denken.</strong><strong>Unterschiedliche Rechtswege ernst nehmen.</strong><strong>Fehler korrigieren, wenn wir heute mehr wissen.</strong></div></section>
<section className="aboutOpen"><p className="sectionLabel">Die Plattform wächst</p><h2>Nicht alles ist fertig. Das ist Absicht.</h2><p>Diese neue Website entsteht schrittweise. Historische Materialien bleiben erreichbar, neue Inhalte werden geprüft ergänzt und die Länderarchitektur wird nur dort konkret, wo es auch eine belastbare Grundlage gibt.</p><div className="heroActions"><a className="buttonPrimary" href="/mitmachen">Mitmachen</a><a className="textLink" href="/aktuelles">Aktuellen Stand ansehen →</a></div></section>
<footer><div className="footerIdentity"><Mark/><div><strong>Rechte der Natur</strong><small>Über uns</small></div></div><p>Herkunft, Verantwortung und fachliche Trennung transparent machen.</p><span>Entwurf · Preview</span></footer>
</main>}
