const paths=[
  {title:"Mitdenken",text:"Du kennst ein Bundesland, einen Naturraum, ein Verfahren oder eine juristische Besonderheit, die wir berücksichtigen sollten? Hinweise sind willkommen – aber wir trennen Anregung und Beleg sauber."},
  {title:"Mitprüfen",text:"Rechte der Natur brauchen belastbare Grundlagen. Wer juristisch, wissenschaftlich oder institutionell beitragen kann, hilft uns besonders bei Länderprüfungen, internationalen Fällen und Quellenchecks."},
  {title:"Mitaufbauen",text:"Eine Initiative entsteht nicht aus einer Website. Wenn in einem Bundesland ein tragfähiger Kreis wachsen soll, braucht es Menschen vor Ort, die Verantwortung übernehmen."},
  {title:"Mitgestalten",text:"Kampagne bedeutet auch Sprache, Bilder, Veranstaltungen, Pressearbeit und gute Materialien. Wer kommunikativ oder gestalterisch beitragen möchte, kann Teil der gemeinsamen Plattform werden."}
];
function Mark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function Mitmachen(){return <main className="joinPage">
<header className="siteHeader"><a className="brand" href="/"><Mark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Mitmachen</small></span></a><nav><a href="/aktuelles">Aktuelles</a><a href="/deutschland">Deutschland</a><a href="/volksbegehren">Volksbegehren</a><a href="/ueber-uns">Über uns</a></nav></header>
<section className="heritageStrip"><span>Gib der Natur Recht.</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Mitdenken statt nur liken.</span></section>
<section className="joinHero"><p className="eyebrow">Mitmachen</p><h1>Diese Plattform soll nicht nur senden.</h1><p className="lead">Rechte der Natur werden nur dann mehr als eine gute Idee, wenn Menschen Wissen, Zeit, Kritik, Kontakte und Verantwortung einbringen. Nicht jeder Beitrag muss eine Kampagne sein.</p></section>
<section className="joinWays">{paths.map((p,i)=><article key={p.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{p.title}</h2><p>{p.text}</p></article>)}</section>
<section className="joinRule"><div><p className="sectionLabel">Unser Anspruch</p><h2>Begeisterung ja. Behauptungen nein.</h2></div><div><p>Wir freuen uns über Hinweise, Ideen und Kontakte. Aber bevor etwas als rechtlicher Stand, internationale Entwicklung oder Kampagnenstatus auf dieser Plattform erscheint, wird es geprüft und eingeordnet.</p><p>Das macht die Arbeit manchmal langsamer. Dafür bleibt sie belastbarer.</p></div></section>
<section className="joinStates"><div><p className="sectionLabel">16 Länder</p><h2>Du willst in deinem Bundesland anfangen?</h2><p>Dann ist der erste Schritt nicht die Unterschriftenliste. Erst schauen wir gemeinsam auf Rechtslage, Verfahren, mögliche Zielsetzung und vorhandene Menschen vor Ort.</p></div><div className="joinSteps"><span>01 · Land und Ausgangslage beschreiben</span><span>02 · vorhandene Kontakte und Initiativen klären</span><span>03 · rechtliche Möglichkeiten prüfen</span><span>04 · erst dann über Kampagne sprechen</span></div></section>
<section className="joinContact"><p className="sectionLabel">Kontakt</p><h2>Schreib uns, woran du mitarbeiten möchtest.</h2><p>Eine direkte Kontaktfunktion wird hier noch eingebaut. Bis dahin entsteht diese Seite als Vorschau der künftigen Beteiligungsstruktur.</p><a className="buttonPrimary" href="/deutschland">Vorher die Länderübersicht ansehen →</a></section>
<footer><div className="footerIdentity"><Mark/><div><strong>Rechte der Natur</strong><small>Mitmachen</small></div></div><p>Wissen, Kritik und Verantwortung zusammenbringen.</p><span>Entwurf · Preview</span></footer>
</main>}
