import Link from "next/link";
import SiteHeader from "../../components/SiteHeader";
import BrandMark from "../../components/BrandMark";
const title="Woher wissen wir, welche Arten wir nicht brauchen?";
const description="Je stärker wir Landschaften auf wenige menschlich gewünschte Funktionen vereinheitlichen, desto leichter erscheinen Arten entbehrlich. Doch kennen wir ihre Möglichkeiten überhaupt?";
const image="https://rechtedernatur.de/images/FE6C03CC-8703-4A37-87CC-15EF33ADEBFB.png";
const notes=[
["Hector, A.; Bagchi, R. (2007): Biodiversity and ecosystem multifunctionality. Nature 448, 188–190.","https://doi.org/10.1038/nature05947"],
["Evans, D. L.; Falagán, N.; Hardman, C. A.; Kourmpetli, S.; Liu, L.; Mead, B. R.; Davies, J. A. C. (2022): Ecosystem service delivery by urban agriculture and green infrastructure – a systematic review. Ecosystem Services 54, 101405.","https://doi.org/10.1016/j.ecoser.2022.101405"],
["Engler, N.; Krarti, M. (2021): Review of energy efficiency in controlled environment agriculture. Renewable and Sustainable Energy Reviews 141, 110786.","https://doi.org/10.1016/j.rser.2021.110786"],
["Severinghaus, J. P.; Broecker, W. S.; Dempster, W. F.; MacCallum, T.; Wahlen, M. (1994): Oxygen loss in Biosphere 2. Eos, Transactions American Geophysical Union 75(3), 33–37.","https://doi.org/10.1029/94EO00285"],
["Silverstone, S. E.; Nelson, M. (1996): Food production and nutrition in Biosphere 2: Results from the first mission September 1991 to September 1993. Advances in Space Research 18(4–5), 49–61.","https://doi.org/10.1016/0273-1177(95)00861-8"],
["Dempster, W. F. (1999): Biosphere 2 engineering design. Ecological Engineering 13, 31–42.","https://doi.org/10.1016/S0925-8574(98)00090-1"],
["Allen, J. P.; Nelson, M. (1999): Biospherics and Biosphere 2, mission one (1991–1993). Ecological Engineering 13, 15–29.","https://doi.org/10.1016/S0925-8574(98)00089-5"],
["Yoshida, S. et al. (2016): A bacterium that degrades and assimilates poly(ethylene terephthalate). Science 351, 1196–1199.","https://doi.org/10.1126/science.aad6359"],
["Eisenhauer, N. et al. (2023): Reconsidering functional redundancy in biodiversity research. npj Biodiversity 2, 9.","https://doi.org/10.1038/s44185-023-00015-5"],
["Fischer, F. M.; de Bello, F. (2023): On the uniqueness of functional redundancy. npj Biodiversity 2, 23.","https://doi.org/10.1038/s44185-023-00029-z"],
["Meyer, S. T. et al. (2018): Biodiversity–multifunctionality relationships depend on identity and number of measured functions. Nature Ecology & Evolution.","https://doi.org/10.1038/s41559-017-0391-4"],
["Gamfeldt, L.; Roger, F. (2017): Revisiting the biodiversity–ecosystem multifunctionality relationship. Nature Ecology & Evolution.","https://doi.org/10.1038/s41559-017-0168"],
["Faith, D. P. (2021): Valuation and Appreciation of Biodiversity: The “Maintenance of Options” Provided by the Variety of Life. Frontiers in Ecology and Evolution 9:635670.","https://doi.org/10.3389/fevo.2021.635670"],
["Mora, C. et al. (2011): How Many Species Are There on Earth and in the Ocean? PLOS Biology 9(8): e1001127.","https://doi.org/10.1371/journal.pbio.1001127"]];
const N=({n,id}:{n:number,id:string})=><sup id={id}><a href={"#note-"+n} aria-label={"Endnote "+n}>[{n}]</a></sup>;
export const metadata={title:`${title} | Rechte der Natur`,description,alternates:{canonical:"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum",languages:{"de":"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum","en":"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum/en","es":"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum/es"}},openGraph:{title,description,type:"article",url:"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum",siteName:"Rechte der Natur",images:[{url:image,width:1536,height:1024,type:"image/png",alt:"Biologischer Möglichkeitsraum zwischen vereinheitlichter Nutzung und biologischer Vielfalt"}]},twitter:{card:"summary_large_image",title,description,images:[image]}};
export default function Artikel(){return <main className="newsPage"><SiteHeader section="Aktuelles" claimLead="Was sich bewegt." claimTrail="Geprüft. Eingeordnet. In Bewegung."/>
<section className="newsHero"><p className="eyebrow">Biodiversität · 19. September 2026</p><h1>Woher wissen wir,<br/>welche Arten wir nicht brauchen?</h1><p className="lead">{description}</p><nav aria-label="Sprachauswahl" style={{display:"flex",gap:10,marginTop:24,fontWeight:700}}><span aria-current="page">DE</span><Link href="/aktuelles/artenvielfalt-moeglichkeitsraum/en">EN</Link><Link href="/aktuelles/artenvielfalt-moeglichkeitsraum/es">ES</Link></nav></section>
<div style={{maxWidth:1100,margin:"0 auto 42px",padding:"0 28px"}}><img src={image} alt="Biologischer Möglichkeitsraum zwischen vereinheitlichter Nutzung und biologischer Vielfalt" style={{display:"block",width:"100%",height:"auto",borderRadius:20}} /></div>
<article style={{maxWidth:860,margin:"0 auto",padding:"0 28px 72px",fontSize:"1.08rem",lineHeight:1.75}}>
<p>Wir gestalten Landschaften immer stärker nach unseren Bedürfnissen. Was dort keinen erkennbaren Zweck erfüllt, erscheint schnell entbehrlich. Doch genau darin steckt ein Denkfehler: Wir beurteilen Arten nach Funktionen, die wir bereits kennen – obwohl wir einen erheblichen Teil ihrer Fähigkeiten und Beziehungen noch gar nicht verstanden haben.</p>
<p>Stellen wir uns eine Landschaft vor, die konsequent auf menschliche Bedürfnisse zugeschnitten ist. Auf dem Acker wächst, was wir essen oder wirtschaftlich verwerten wollen. Der Wald liefert Holz. Flüsse werden so gestaltet, dass Wasser verfügbar ist und Hochwasser möglichst beherrschbar bleibt. Straßen verbinden Siedlungen, Gewerbegebiete schaffen Arbeitsplätze, Grünflächen erfüllen definierte Funktionen.</p><p>Je konsequenter wir eine solche Landschaft optimieren, desto naheliegender erscheint eine zunächst provozierende Frage: <strong>Wozu brauchen wir eigentlich noch so viele Arten?</strong></p>
<h2>Für Mais braucht man nicht jede Art</h2><p>Wenn wir nur eine einzelne Funktion betrachten, ist keineswegs jede vorhandene Art dafür unverzichtbar. Ein Maisacker muss nicht die Artenvielfalt einer natürlichen oder naturnäheren Landschaft besitzen, um Mais zu produzieren. Auch die Biodiversitätsforschung zeigt, dass einzelne Ökosystemfunktionen sättigende Beziehungen zur Artenvielfalt aufweisen können. Betrachtet man mehrere Funktionen, werden mehr Arten benötigt, weil unterschiedliche Arten unterschiedliche Funktionen tragen können.<N n={1} id="ref-1"/></p><p>Genau hier beginnt der Denkfehler. Denn bevor wir feststellen, welche Arten wir „brauchen“, haben wir bereits entschieden, wofür wir sie brauchen. Die Nutzung bestimmt die Funktion. Und die Funktion bestimmt anschließend, was uns als nützlich oder überflüssig erscheint.</p>
<h2>Wie weit können wir das Ökosystem weglassen?</h2><p>Der Einwand lässt sich noch weiter treiben. Wenn wir für eine bestimmte Produktion tatsächlich nicht die ganze biologische Vielfalt einer Landschaft benötigen: Können wir dann nicht immer mehr ökologische Voraussetzungen technisch ersetzen?</p><p>„Urban Farming“ bezeichnet vor allem den urbanen Kontext, nicht den Grad technischer Kontrolle, und umfasst sehr unterschiedliche Systeme – von Gemeinschaftsgärten bis zu technisch kontrollierten Vertical Farms. Gemeinschaftsgärten gehören laut einer systematischen Übersichtsarbeit zu den urbanen Anbau- und Grünflächen, die besonders vielfältige Ökosystemleistungen bereitstellen.<N n={2} id="ref-2"/></p><p>Bei technisch kontrollierter Indoor- oder Vertical-Farming-Produktion, städtisch oder nicht, können Licht, Temperatur, Luftfeuchtigkeit, Wasser und Nährstoffversorgung gezielt technisch kontrolliert oder bereitgestellt werden. Für bestimmte Kulturen lässt sich die Produktion damit von Witterung und Standortbedingungen weitgehend entkoppeln.<N n={3} id="ref-3"/></p><p>Die Voraussetzungen dieser Produktion verschwinden damit nicht. Beleuchtung, Klimatisierung, Pumpen und Steuerung benötigen Energie und technische Infrastruktur; wesentliche Voraussetzungen können also außerhalb der Farm liegen.<N n={3} id="ref-3b"/></p><p>Eine Vertical Farm muss allerdings auch kein vollständiges Ökosystem reproduzieren. Sie soll beispielsweise Salat oder Kräuter produzieren. Was geschieht, wenn wir die Systemgrenze viel weiter ziehen?</p>
<h2>Was Biosphere 2 sichtbar machte</h2><p>Anfang der 1990er-Jahre wurde in Arizona in ungewöhnlichem Maßstab eine verwandte Frage praktisch erprobt. Biosphere 2 war eine weitgehend luftdichte, verglaste Anlage mit künstlich zusammengestellten Lebensräumen, Böden, Wasser, Atmosphäre, Pflanzen und Tieren.<N n={14} id="ref-14"/><N n={11} id="ref-11"/> Acht Menschen lebten während der ersten Mission zwei Jahre darin. Das interne Agrarsystem deckte rund 80 Prozent ihres Ernährungsbedarfs.<N n={10} id="ref-10"/></p><p>Gerade deshalb wäre es falsch, Biosphere 2 einfach als gescheitertes Experiment zu beschreiben. Interessant sind vielmehr die Wechselwirkungen, die in dem weitgehend geschlossenen System sichtbar wurden.</p><p>Während der ersten 16 Monate sank der Sauerstoffgehalt der Atmosphäre von ungefähr 21 auf 14 Prozent. Untersuchungen führten den Sauerstoffverlust wesentlich auf die Atmung von Mikroorganismen in den stark mit organischem Material angereicherten Böden zurück. Das dabei entstehende Kohlendioxid blieb jedoch nicht vollständig in der Atmosphäre: Ein Teil reagierte mit dem verbauten Beton zu Calciumcarbonat.<N n={4} id="ref-4b"/></p><p>Ein biologischer Prozess im Boden, die Zusammensetzung der Atmosphäre und die Chemie eines Baustoffs waren damit unmittelbar miteinander gekoppelt.</p><p>Biosphere 2 war auf weitgehende materielle Geschlossenheit angelegt; Energie wurde jedoch von außen zugeführt.<N n={6} id="ref-6b"/> Als der Sauerstoffgehalt nach rund 16 Monaten auf etwa 14 Prozent gefallen war, wurde zusätzlich Sauerstoff von außen eingespeist.<N n={12} id="ref-12"/></p><p>Das Experiment zeigt deshalb nicht, dass Menschen keine künstlich organisierten Ökosysteme bauen können. Es veranschaulicht etwas für unsere Ausgangsfrage Interessanteres: In einem weitgehend geschlossenen System können Wechselwirkungen zwischen Boden, Atmosphäre und Baustoffen sichtbar werden, die bei der Optimierung einzelner Funktionen leicht außerhalb des Blickfelds bleiben.</p><p>Doch selbst damit bleibt eine zweite Unsicherheit. Wir kennen nicht nur die Beziehungen eines komplexen Systems unvollständig. Wir kennen auch die Fähigkeiten seiner einzelnen Organismen nur teilweise.</p>
<h2>Ein Bakterium und eine Plastikflasche</h2><p>2016 identifizierten Forschende das Bakterium <em>Ideonella sakaiensis</em>. Unter den untersuchten Laborbedingungen kann es PET abbauen und die Abbauprodukte assimilieren.<N n={13} id="ref-13"/> Das löst nicht das globale Plastikproblem. Es illustriert aber, wie schwer vorhersehbar ist, welche biochemischen Fähigkeiten eines Organismus für uns einmal bedeutsam werden können.</p>
<h2>Wann ist eine Art überflüssig?</h2><p>Arten können hinsichtlich einer bestimmten Funktion ähnlich sein. In der Ökologie wurde dafür lange der Begriff der funktionalen Redundanz verwendet. Eisenhauer und Kollegen schlagen vor, präziser von „funktionaler Ähnlichkeit“ zu sprechen und Funktion, Umweltbedingungen und Kontext anzugeben.<N n={14} id="ref-14"/> Fischer und de Bello halten dem entgegen, dass funktionale Redundanz als ökologisches Konzept einen eigenständigen Wert besitzt.<N n={10} id="ref-10"/> Ähnliche Arten können unter heutigen Bedingungen eine vergleichbare Funktion erfüllen und dennoch unterschiedlich auf veränderte Bedingungen reagieren.</p><p>Ökosysteme erfüllen zudem nicht nur eine Funktion. Welche Beziehung zwischen Biodiversität und Multifunktionalität gemessen wird, hängt davon ab, welche Funktionen einbezogen werden und wie viele betrachtet werden.<N n={11} id="ref-11"/> Auch die Auswertungsmethode beeinflusst die gemessene Beziehung.<N n={12} id="ref-12"/></p><p>„Diese Art brauchen wir nicht“ bedeutet daher zunächst nur: Wir brauchen sie nicht für eine bestimmte uns bekannte Funktion, unter bestimmten uns bekannten Bedingungen.</p>
<h2>Der biologische Möglichkeitsraum</h2><p>Im IPBES-Konzept der Beiträge der Natur für die Menschen (<em>Nature’s Contributions to People</em>) bezeichnet <em>maintenance of options</em> (NCP 18) die Fähigkeit von Ökosystemen, Lebensräumen, Arten oder Genotypen, Optionen für ein gutes Leben offenzuhalten.<N n={13} id="ref-13"/> Als „biologischen Möglichkeitsraum“ bezeichnet dieser Beitrag die Gesamtheit dieser Optionen – eine journalistische Verdichtung, kein etablierter Fachbegriff.</p><p>Das bedeutet nicht, dass jede Art irgendwann für Menschen nützlich werden muss. Entscheidend ist die Wissensgrenze. Nicht einmal die Zahl der Arten auf der Erde kennen wir genau. Mora und Kollegen schätzten 2011 rund 8,7 Millionen eukaryotische Arten (± 1,3 Millionen, Standardfehler) und betonten zugleich die Unsicherheiten indirekter Schätzverfahren.<N n={14} id="ref-14"/></p><p>Mit dem Verschwinden einer Art verlieren wir deshalb nicht zwangsläufig eine uns bekannte unverzichtbare Funktion. Es gehen jedoch biologische Möglichkeiten und Beziehungen verloren, von denen wir möglicherweise noch gar nicht wissen, dass sie existieren.</p><p>Aus dieser Wissensgrenze folgt nicht, dass jede Art unter allen Umständen gleich gewichtet werden muss oder Naturschutz ohne Prioritäten auskommt. Entscheidungen über Schutz, Nutzung und Zielkonflikte bleiben notwendig. Sie sollten nur nicht auf der weitergehenden Annahme beruhen, das Fehlen einer heute erkennbaren Funktion mache eine Art entbehrlich.</p><p>Damit ist noch nichts über einen möglichen Eigenwert von Arten gesagt. Dieser Beitrag untersucht bewusst nur die engere, instrumentelle Frage, ob wir ihre Entbehrlichkeit aus unserem gegenwärtigen Wissen ableiten können.</p>
<h2>Die Einheitsnutzfläche hat einen blinden Fleck</h2><p>Je stärker Landschaft zur Einheitsnutzfläche wird, desto stärker bestimmt unser Nutzungszweck, welche Funktionen überhaupt sichtbar und relevant erscheinen. Aus „für unsere gegenwärtige Nutzung nicht erforderlich“ wird beinahe unmerklich „nicht erforderlich“. Das eine folgt aus dem anderen jedoch nicht.</p><p>Technisch kontrollierte Produktionssysteme ändern an diesem Schluss nichts: Sie können einzelne Funktionen isolieren und stabilisieren, ohne damit die Beziehungen und Möglichkeiten eines größeren lebenden Systems zu ersetzen.</p><p><strong>Wir vereinheitlichen die Erde womöglich schneller, als wir ihre biologischen Möglichkeiten kennenlernen.</strong></p>
<h2>Brauchen wir also jede Art?</h2><p>Darauf gibt es keine einfache wissenschaftliche Antwort. Es wäre zu bequem, zu behaupten, jede Art sei für jede denkbare Funktion unverzichtbar. Aber die umgekehrte Behauptung ist mindestens ebenso problematisch.</p><p>Vielleicht lautet die entscheidende Frage deshalb gar nicht: <strong>Wie viele Arten brauchen wir?</strong></p><p>Sondern: <strong>Woher wissen wir eigentlich, welche Arten wir nicht brauchen?</strong></p><p>Solange wir diese Frage nicht beantworten können, ist die Behauptung ihrer Entbehrlichkeit größer als unser Wissen.</p>
<hr/><h2>Quellen und Anmerkungen</h2><ol>{notes.map((x,i)=><li id={"note-"+(i+1)} key={x[1]} style={{marginBottom:12}}><a href={x[1]} target="_blank" rel="noreferrer">{x[0]}</a> <a href={"#ref-"+(i+1)} aria-label={"Zurück zur Textstelle "+(i+1)}>↩</a></li>)}</ol>
<hr/><p style={{fontSize:".9rem"}}><strong>Lizenzhinweis:</strong> Dieser Beitrag einschließlich des begleitenden KI-generierten Bildes steht unter der Lizenz Creative Commons Namensnennung – Nicht kommerziell – Weitergabe unter gleichen Bedingungen 4.0 International (CC BY-NC-SA 4.0).</p><p style={{fontSize:".9rem"}}>Struktur und Teile der Formulierung dieses Textes wurden mithilfe von KI (GPT, OpenAI) entwickelt. Inhaltliche Verantwortung: Hans Leo Bader. (CC BY-NC-SA 4.0)</p><p style={{fontSize:".9rem"}}>Bild (sofern enthalten): In Kooperation mit KI - generiert mit ChatGPT Images (OpenAI) – Lizenz: CC BY-NC-SA 4.0</p></article><footer><div className="footerIdentity"><BrandMark/><div><strong>Rechte der Natur</strong><small>Aktuelles</small></div></div></footer></main>}