import Link from "next/link";
import SiteHeader from "../../components/SiteHeader";
import BrandMark from "../../components/BrandMark";
const title="Woher wissen wir, welche Arten wir nicht brauchen?";
const description="Je stärker wir Landschaften auf wenige menschlich gewünschte Funktionen vereinheitlichen, desto leichter erscheinen Arten entbehrlich. Doch kennen wir ihre Möglichkeiten überhaupt?";
const image="/images/artenvielfalt-moeglichkeitsraum.jpg";
const notes=[
["Hector, A.; Bagchi, R. (2007): Biodiversity and ecosystem multifunctionality. Nature 448, 188–190.","https://doi.org/10.1038/nature05947"],
["Yoshida, S. et al. (2016): A bacterium that degrades and assimilates poly(ethylene terephthalate). Science 351, 1196–1199.","https://doi.org/10.1126/science.aad6359"],
["Dadachova, E. et al. (2007): Ionizing Radiation Changes the Electronic Properties of Melanin and Enhances the Growth of Melanized Fungi. PLOS ONE 2(5): e457.","https://doi.org/10.1371/journal.pone.0000457"],
["Eisenhauer, N. et al. (2023): Reconsidering functional redundancy in biodiversity research. npj Biodiversity 2, 9.","https://doi.org/10.1038/s44185-023-00015-5"],
["Fischer, M.; de Bello, F. (2023): On the uniqueness of functional redundancy. npj Biodiversity 2, 23.","https://doi.org/10.1038/s44185-023-00029-z"],
["Gamfeldt, L.; Roger, F. (2017): Revisiting the biodiversity–ecosystem multifunctionality relationship. Nature Ecology & Evolution.","https://doi.org/10.1038/s41559-017-0168"],
["Meyer, S. T. et al. (2018): Biodiversity–multifunctionality relationships depend on identity and number of measured functions. Nature Ecology & Evolution.","https://doi.org/10.1038/s41559-017-0391-4"],
["Faith, D. P. (2021): Valuation and Appreciation of Biodiversity: The “Maintenance of Options” Provided by the Variety of Life. Frontiers in Ecology and Evolution 9:635670.","https://doi.org/10.3389/fevo.2021.635670"],
["Mora, C. et al. (2011): How Many Species Are There on Earth and in the Ocean? PLOS Biology 9(8): e1001127.","https://doi.org/10.1371/journal.pbio.1001127"]];
const N=({n}:{n:number})=><sup><a href={"#note-"+n} aria-label={"Endnote "+n}>[{n}]</a></sup>;
export const metadata={title:`${title} | Rechte der Natur`,description,openGraph:{title,description,type:"article",url:"https://rechtedernatur.de/aktuelles/artenvielfalt-moeglichkeitsraum",siteName:"Rechte der Natur"},twitter:{card:"summary_large_image",title,description}};
export default function Artikel(){return <main className="newsPage"><SiteHeader section="Aktuelles" claimLead="Was sich bewegt." claimTrail="Geprüft. Eingeordnet. In Bewegung."/>
<section className="newsHero"><p className="eyebrow">Biodiversität · 19. September 2026</p><h1>{title}</h1><p className="lead">{description}</p><nav aria-label="Sprachauswahl" style={{display:"flex",gap:10,marginTop:24,fontWeight:700}}><span aria-current="page">DE</span><Link href="/aktuelles/artenvielfalt-moeglichkeitsraum/en">EN</Link><Link href="/aktuelles/artenvielfalt-moeglichkeitsraum/es">ES</Link></nav></section>
<div style={{maxWidth:1100,margin:"0 auto 42px",padding:"0 28px",borderRadius:20,background:"rgba(0,0,0,.035)",minHeight:320,display:"grid",placeItems:"center"}}><p style={{opacity:.6}}>Titelbild folgt</p></div>
<article style={{maxWidth:860,margin:"0 auto",padding:"0 28px 72px",fontSize:"1.08rem",lineHeight:1.75}}>
<p>Wir gestalten Landschaften immer stärker nach unseren Bedürfnissen. Was dort keinen erkennbaren Zweck erfüllt, erscheint schnell entbehrlich. Doch genau darin steckt ein Denkfehler: Wir beurteilen Arten nach Funktionen, die wir bereits kennen – obwohl wir einen erheblichen Teil ihrer Fähigkeiten und Beziehungen noch gar nicht verstanden haben.</p>
<p>Stellen wir uns eine Landschaft vor, die konsequent auf menschliche Bedürfnisse zugeschnitten ist. Auf dem Acker wächst, was wir essen oder wirtschaftlich verwerten wollen. Der Wald liefert Holz. Flüsse werden so gestaltet, dass Wasser verfügbar ist und Hochwasser möglichst beherrschbar bleibt. Straßen verbinden Siedlungen, Gewerbegebiete schaffen Arbeitsplätze, Grünflächen erfüllen definierte Funktionen.</p><p>Je konsequenter wir eine solche Landschaft optimieren, desto naheliegender erscheint eine zunächst provozierende Frage: <strong>Wozu brauchen wir eigentlich noch so viele Arten?</strong></p>
<h2>Für Mais braucht man nicht jede Art</h2><p>Wenn wir nur eine einzelne Funktion betrachten, ist keineswegs jede vorhandene Art dafür unverzichtbar. Ein Maisacker muss nicht die Artenvielfalt einer natürlichen oder naturnäheren Landschaft besitzen, um Mais zu produzieren. Auch die Biodiversitätsforschung zeigt, dass einzelne Ökosystemfunktionen sättigende Beziehungen zur Artenvielfalt aufweisen können. Betrachtet man mehrere Funktionen, wird das Bild komplexer.<N n={1}/></p><p>Genau hier beginnt der Denkfehler. Denn bevor wir feststellen, welche Arten wir „brauchen“, haben wir bereits entschieden, wofür wir sie brauchen. Die Nutzung bestimmt die Funktion. Und die Funktion bestimmt anschließend, was uns als nützlich oder überflüssig erscheint.</p>
<h2>Ein Bakterium und eine Plastikflasche</h2><p>2016 identifizierten Forschende das Bakterium <em>Ideonella sakaiensis</em>. Es kann PET abbauen und die Abbauprodukte assimilieren.<N n={2}/> Daraus sollte man keine Wundergeschichte machen. Interessant ist etwas anderes: Wir finden einen Organismus, dessen biochemische Ausstattung den Abbau dieses menschengemachten Materials ermöglicht. Hätten wir vorher gewusst, dass gerade dieses Bakterium einmal eine für Menschen interessante Fähigkeit besitzen würde? Wahrscheinlich nicht.</p>
<h2>Leben unter Strahlung</h2><p>Der melanisierte Pilz <em>Cladosporium sphaerospermum</em> wurde in Tschernobyl in radioaktiv belasteten Bereichen beobachtet. Laboruntersuchungen zeigten, dass ionisierende Strahlung die elektronischen Eigenschaften von Melanin verändert; bei untersuchten melanisierten Pilzen wurde unter Strahlenexposition zugleich verstärktes Wachstum beobachtet.<N n={3}/> Die spektakuläre Formulierung, solche Pilze würden sich „von Radioaktivität ernähren“, geht über diesen Befund hinaus.</p><p>PET und Tschernobyl beweisen nicht, dass die Natur für jedes menschlich verursachte Problem eine Lösung bereithält. Sie zeigen etwas Grundsätzlicheres: <strong>Wir wissen nicht vollständig, wozu Leben fähig ist.</strong></p>
<h2>Wann ist eine Art überflüssig?</h2><p>Arten können hinsichtlich einer bestimmten Funktion ähnlich sein. In der Ökologie wurde dafür lange der Begriff der funktionalen Redundanz verwendet. Eisenhauer und Kollegen schlagen vor, präziser von „funktionaler Ähnlichkeit“ zu sprechen und Funktion, Umweltbedingungen und Kontext anzugeben.<N n={4}/> Fischer und de Bello halten dem entgegen, dass funktionale Redundanz als ökologisches Konzept einen eigenständigen Wert besitzt.<N n={5}/></p><p>Ökosysteme erfüllen zudem nicht nur eine Funktion. Welche Beziehung zwischen Biodiversität und Multifunktionalität gemessen wird, hängt auch davon ab, welche und wie viele Funktionen betrachtet werden.<N n={1}/><N n={6}/><N n={7}/></p><p>„Diese Art brauchen wir nicht“ bedeutet daher zunächst nur: Wir brauchen sie nicht für eine bestimmte uns bekannte Funktion, unter bestimmten uns bekannten Bedingungen.</p>
<h2>Der biologische Möglichkeitsraum</h2><p>In der Biodiversitätsforschung wird die Erhaltung von Optionen – <em>maintenance of options</em> – als wichtiger Wert diskutiert: Biodiversität kann Optionen für zukünftige Beiträge zur Lebensqualität offenhalten.<N n={8}/> Man könnte von einem biologischen Möglichkeitsraum sprechen.</p><p>Das bedeutet nicht, dass jede Art irgendwann für Menschen nützlich werden muss. Entscheidend ist die Wissensgrenze. Nicht einmal die Zahl der Arten auf der Erde kennen wir genau. Mora und Kollegen schätzten 2011 rund 8,7 Millionen eukaryotische Arten und betonten zugleich die Unsicherheiten indirekter Schätzverfahren.<N n={9}/></p><p>Mit dem Verschwinden einer Art verlieren wir deshalb nicht zwangsläufig eine uns bekannte unverzichtbare Funktion. Es gehen jedoch biologische Möglichkeiten und Beziehungen verloren, von denen wir möglicherweise noch gar nicht wissen, dass sie existieren.</p>
<h2>Die Einheitsnutzfläche hat einen blinden Fleck</h2><p>Je stärker Landschaft zur Einheitsnutzfläche wird, desto stärker bestimmt unser Nutzungszweck, welche Funktionen überhaupt sichtbar und relevant erscheinen. Aus „für unsere gegenwärtige Nutzung nicht erforderlich“ wird beinahe unmerklich „nicht erforderlich“. Das eine folgt aus dem anderen jedoch nicht.</p><p><strong>Wir vereinheitlichen die Erde womöglich schneller, als wir ihre biologischen Möglichkeiten kennenlernen.</strong></p>
<h2>Brauchen wir also jede Art?</h2><p>Darauf gibt es keine einfache wissenschaftliche Antwort. Es wäre zu bequem, zu behaupten, jede Art sei für jede denkbare Funktion unverzichtbar. Aber die umgekehrte Behauptung ist mindestens ebenso problematisch.</p><p>Vielleicht lautet die entscheidende Frage deshalb gar nicht: <strong>Wie viele Arten brauchen wir?</strong></p><p>Sondern: <strong>Woher wissen wir eigentlich, welche Arten wir nicht brauchen?</strong></p><p>Solange wir diese Frage nicht beantworten können, ist die Behauptung ihrer Entbehrlichkeit größer als unser Wissen.</p>
<hr/><h2>Quellen und Anmerkungen</h2><ol>{notes.map((x,i)=><li id={"note-"+(i+1)} key={x[1]} style={{marginBottom:12}}><a href={x[1]} target="_blank" rel="noreferrer">{x[0]}</a> <a href="#" aria-label={"Zurück aus Endnote "+(i+1)}>↩</a></li>)}</ol>
<hr/><p style={{fontSize:".9rem"}}><strong>Lizenzhinweis:</strong> Dieser Beitrag einschließlich des begleitenden KI-generierten Bildes steht unter der Lizenz Creative Commons Namensnennung – Nicht kommerziell 4.0 International (CC BY-NC-SA 4.0).</p><p style={{fontSize:".9rem"}}>Struktur und Teile der Formulierung dieses Textes wurden mithilfe von KI (GPT, OpenAI) entwickelt. Inhaltliche Verantwortung: Hans Leo Bader. (CC BY-NC-SA 4.0)</p><p style={{fontSize:".9rem"}}>Bild (sofern enthalten): In Kooperation mit KI - generiert mit ChatGPT Images (OpenAI) – Lizenz: CC BY-NC-SA 4.0</p></article><footer><div className="footerIdentity"><BrandMark/><div><strong>Rechte der Natur</strong><small>Aktuelles</small></div></div></footer></main>}