import "./weltweit.css";

const cases=[
  {region:"Ecuador",title:"Natur in der Verfassung",type:"Verfassung",year:"2008",text:"Ecuador verankerte Rechte der Natur auf Verfassungsebene. Damit wurde aus einer politischen Idee ein verfassungsrechtlicher Bezugspunkt – aber noch keine Garantie für eine einheitliche Praxis."},
  {region:"Ecuador",title:"Los Cedros",type:"Gericht",year:"2021",text:"Im Fall des Schutzwalds Los Cedros wurde sichtbar, wie Rechte der Natur in einer konkreten gerichtlichen Entscheidung Bedeutung entfalten können."},
  {region:"Kolumbien",title:"Río Atrato",type:"Gericht + Vertretung",year:"2016",text:"Der Atrato wurde als Rechtssubjekt anerkannt. Entscheidend war dabei nicht nur die Anerkennung selbst, sondern auch die Frage, wer den Fluss künftig vertreten und seine Belange in Verfahren einbringen soll."},
  {region:"Aotearoa / Neuseeland",title:"Whanganui",type:"Gesetz + Vertretung",year:"2017",text:"Der Whanganui erhielt eine eigene Rechtspersönlichkeit innerhalb einer gesetzlich geregelten Vertretungsordnung. Das Modell verbindet staatliches Recht mit einer anderen Beziehung zwischen Menschen und Fluss."},
  {region:"Aotearoa / Neuseeland",title:"Te Urewera",type:"Gesetz + Governance",year:"2014",text:"Te Urewera ist nicht mehr bloß staatliches Eigentum. Die rechtliche Konstruktion ordnet Verantwortung und Governance neu und zeigt, dass Rechte der Natur nicht auf Flüsse begrenzt sind."},
  {region:"Spanien",title:"Mar Menor",type:"Gesetz + Institutionen",year:"2022",text:"Die Lagune Mar Menor erhielt eigene Rechte. Der Fall zeigt besonders deutlich, dass Rechtsträgerschaft, Vertretung, Aufsicht und tatsächliche ökologische Wirkung getrennt betrachtet werden müssen."}
];
const lenses=[
  ["Anerkennung","Hat Natur eine eigene rechtliche Stellung – und auf welcher Ebene: Verfassung, Gesetz oder Gericht?"],
  ["Vertretung","Wer darf oder muss für das betroffene Ökosystem handeln?"],
  ["Institutionen","Welche Gremien, Verfahren und Zuständigkeiten sorgen dafür, dass die Rechte nicht nur auf dem Papier stehen?"],
  ["Wirkung","Verändert sich eine konkrete Entscheidung, ein Vollzug oder der Zustand des Ökosystems tatsächlich?"]
];
function Mark(){return <span className="brandMark" aria-hidden="true"><i/><i/><i/><i/><b>⌁</b></span>}
export default function Weltweit(){return <main className="worldPage">
<header className="siteHeader"><a className="brand" href="/"><Mark/><span className="brandWords"><strong>Rechte der Natur</strong><small>Weltweit</small></span></a><nav><a href="/">Die Idee</a><a href="/deutschland">Deutschland</a><a href="/volksbegehren">Volksbegehren</a><a className="navAction" href="#faelle">Fälle ansehen</a></nav></header>
<section className="heritageStrip"><span>Rechte der Natur</span><span className="heritageColors"><i/><i/><i/><i/></span><span>Viele Rechtswege. Viele Erfahrungen.</span></section>
<section className="worldHero"><div><p className="eyebrow">Weltweit</p><h1>Die Idee hat viele Formen angenommen.</h1><p className="lead">Verfassungen, Gesetze und Gerichte haben Natur in unterschiedlichen Rechtsordnungen eine eigenständige Stellung gegeben. Entscheidend ist nicht nur, ob ein Recht anerkannt wird – sondern wie es vertreten, institutionell aufgenommen und tatsächlich wirksam wird.</p><div className="heroActions"><a className="buttonPrimary" href="#faelle">Fälle entdecken</a><a className="textLink" href="#lesen">Wie wir sie lesen →</a></div></div><div className="worldOrb" aria-hidden="true"><span>Wald</span><span>Fluss</span><span>Lagune</span><span>Land</span></div></section>
<section className="worldRead" id="lesen"><div><p className="sectionLabel">Wie wir hinschauen</p><h2>Keine Sammlung von Erfolgsgeschichten.</h2></div><div><p>Rechte der Natur werden oft so erzählt, als sei die Anerkennung selbst schon der entscheidende Erfolg. Das greift zu kurz.</p><p>Wir fragen deshalb bei jedem Fall: Was wurde rechtlich verändert? Wer kann handeln? Welche Institutionen tragen die neue Stellung? Und lässt sich eine tatsächliche Wirkung erkennen?</p></div></section>
<section className="lensGrid">{lenses.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</section>
<section className="worldCases" id="faelle"><div className="stateHeader"><p className="sectionLabel">Falllandschaft</p><h2>Sechs Fälle. Sechs unterschiedliche rechtliche Konstruktionen.</h2><p>Diese Auswahl ist kein Ranking. Sie zeigt, wie unterschiedlich Rechte der Natur ausgestaltet werden können.</p></div><div className="caseLandscape">{cases.map((c,i)=><article key={c.title}><div className="caseMeta"><span>{c.region}</span><strong>{c.year}</strong></div><h3>{c.title}</h3><em>{c.type}</em><p>{c.text}</p><span className="caseMore">Vertiefung entsteht hier →</span></article>)}</div></section>
<section className="worldCompare"><div><p className="sectionLabel">Was sich vergleichen lässt</p><h2>Rechtsträgerschaft ist nur der Anfang.</h2></div><div className="compareStack"><article><strong>1</strong><span>Anerkennung</span></article><article><strong>2</strong><span>Vertretung</span></article><article><strong>3</strong><span>Institutionelle Aufnahme</span></article><article><strong>4</strong><span>Entscheidung und Vollzug</span></article><article><strong>5</strong><span>Wirkung in der Mitwelt</span></article></div></section>
<section className="worldBridge"><p className="sectionLabel">Und Deutschland?</p><h2>Internationale Modelle lassen sich nicht einfach kopieren.</h2><p>Sie können aber zeigen, welche Fragen geklärt werden müssen, bevor aus einer guten Idee eine tragfähige Rechtsentwicklung wird.</p><div className="heroActions"><a className="buttonPrimary" href="/deutschland">Zur Deutschlandseite</a><a className="textLink" href="/volksbegehren">Zu den Volksbegehren →</a></div></section>
<footer><div className="footerIdentity"><Mark/><div><strong>Rechte der Natur</strong><small>Weltweit</small></div></div><p>Internationale Rechtsentwicklungen verständlich vergleichen.</p><span>Entwurf · Preview</span></footer>
</main>}
